kind: pipeline
type: docker
name: deploy

trigger:
  branch:
  - main
  event:
  - tag
  ref:
  - refs/tags/v[0-9]*

steps:
  - name: build-composer
    image: composer
    commands:
      - composer install --ignore-platform-reqs

  - name: create-zip
    image: javieraviles/zip
    commands:
      - mv trunk woocommerce-zaver-checkout
      - zip -r woocommerce-zaver-checkout-latest.zip woocommerce-zaver-checkout
      - cp woocommerce-zaver-checkout-latest.zip woocommerce-zaver-checkout-${DRONE_TAG}.zip

  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: wm-static
      access_key:
        from_secret: s3_key
      secret_key:
        from_secret: s3_secret
      source: woocommerce-zaver-checkout-*.zip
      target: /zaver/woocommerce-zaver-checkout
      endpoint: https://fra1.digitaloceanspaces.com
      acl: public-read