name: Test installing plugin on InstaWP staging site

on:
  push:
    branches:
      - '**'

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.INSTAWP_DEPLOY_SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H zaver-checkout-test.krokedil.site >> ~/.ssh/known_hosts

    - name: SSH into server and install plugin from Amazon S3 bucket
      run: |
        ssh -o StrictHostKeyChecking=no beviranudi5807@zaver-checkout-test.krokedil.site "cd ~/web/zaver-checkout-test.krokedil.site/public_html && wp plugin install https://krokedil-plugin-dev-zip.s3.eu-north-1.amazonaws.com/avarda-checkout-for-woocommerce-dev-develop-fix-shipping-widget-error-48eae3c.zip --activate --force --skip-plugins --skip-themes"