name: Test SSH

on:
  push:
    branches:
      - '**'

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.INSTAWP_DEPLOY_SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H zaver-checkout-test.krokedil.site >> ~/.ssh/known_hosts

    - name: Create and execute shell script on server
      run: |
        ssh beviranudi5807@zaver-checkout-test.krokedil.site "echo 'ls -l ~' > ~/check_home_dir.sh"
        ssh beviranudi5807@zaver-checkout-test.krokedil.site "chmod +x ~/check_home_dir.sh"
        ssh beviranudi5807@zaver-checkout-test.krokedil.site "~/check_home_dir.sh" || echo "Home directory contents not found"